### ISSUE TITLE
Default for ingress.tls.secretName

### ISSUE THREAD

**Issue by hairmare** [adfinis-sygroup/timed-chart#15]
We should default `ingress.tls.secretName` to something like `{{ include "timed.fullname" . }}-tls`.

Right now the secretName is something I've been changing to match the release name in all the cases I know of.

**Comment by strixBE** [comment]
This would mean fixing the structure of `ingress.tls` which does not seem the best way to go:

```yaml
# values.yaml
ingress:
  enabled: false
  tls:
    enabled: false
    hosts: []
```

```yaml
# templates/ingress.yaml
ingress:
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - secretName: {{ include "timed.fullname" . }}
      hosts:
{{ toYaml .Values.ingress.tls.hosts | indent 6 }}
```

This seems much more complex and you cannot override all tls params
