### ISSUE TITLE
Possibility to overwrite work report ots

### ISSUE THREAD

**Issue by sliverc** [adfinis-sygroup/timed-chart#6]
`DJANGO_WORK_REPORT_PATH` needs to be set and file mounted into container.

We can potentially use https://docs.helm.sh/chart_template_guide/#accessing-files-inside-templates although not sure whether this is enough as work report is a binary file.

**Comment by MrStrix** [comment]
It seems like we still have to address this issue. If I understand correctly `DJANGO_WORK_REPORT_PATH` should point to a .ots (Libreoffice Spreadsheet Template) file and this file should be uploaded and mounted.

I suggest using the `ConfigMap`'s `binaryData` field to store the file:
* https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.10.md#apps
* https://stackoverflow.com/questions/51337874/kubernetes-helm-any-examples-with-configmap-and-binarydata

```
configmap-workreport.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: django-work-report
data:
binaryData:
  workreport.ots: |-
    {{ .Files.Get "workreport.ots" | b64enc }}
```

The question is, how to mount (and `b64dec`) it when passing to the container.
